const COFFEE_ORDERED = "COFFEE_ORDERED";
const COFFEE_RESTOCKED = "COFFEE_RESTOCKED";
const COFFEEBEAN_ORDERED = "COFFEEBEAN_ORDERED";
const COFFEEBEAN_RESTOCKED = "COFFEEBEAN_RESTOCKED";
const CAKE_ORDERED = "CAKE_ORDERED";
const CAKE_RESTOCKED = "CAKE_RESTOCKED";
const POKEMON_PENDING = "POKEMON_PENDING";
const POKEMON_SUCCESSED = "POKEMON_SUCCESSED";
const POKEMON_FAILED = "POKEMON_FAILED";

module.exports = {
  COFFEE_ORDERED, //咖啡的購買
  COFFEE_RESTOCKED, //咖啡的補貨
  COFFEEBEAN_ORDERED, //咖啡豆的購買
  COFFEEBEAN_RESTOCKED, //咖啡豆的補貨
  CAKE_ORDERED, //蛋糕的購買
  CAKE_RESTOCKED, //蛋糕的補貨
  POKEMON_PENDING,
  POKEMON_SUCCESSED,
  POKEMON_FAILED,
};
